### ISSUE TITLE
Auth error using the app locally

### ISSUE THREAD

**Issue by brunomoleta** [Dantalian5/product-feedback-app#1]
(same comment at Front end Mentor)

Hi,
after setting the local ``DATABASE_URL`` at ``.env``, running ``prisma generate`` and starting the app,
at the moment where you try to register an account the app returns:

````
ClientFetchError: There was a problem with the server configuration. Check the server logs for more information.. Read more at [https://errors.authjs.dev#autherror](https://errors.authjs.dev/#autherror)
````

**Comment by Dantalian5** [comment]
Hi Bruno, as always, it’s a pleasure to have you on board. I’m sorry for the problems you’ve encountered. I believe they are entirely due to the very poor documentation I wrote, in addition to not specifying the setup steps clearly. I have recreated everything from scratch, and the errors occurred due to not initializing Prisma and the auth_secret. In this case, please follow these steps and let me know if the problem is resolved.

1. Configure db url on .env

   ```
   DATABASE_URL=postgresql://user:password@host_ip/db_name
   ```

2. Configure auth secret on .env

   run `npx auth secret`
   or `openssl rand -base64 33` and addit to .env

   ```
   AUTH_SECRET=mlxIMVkGGd6REqFh8WrVd+SHUV9G7UV8VuvE6/QA0LSh
   ```

3. Run `npx prisma migrate dev --name init` to sync prisma with the database

**Comment by Dantalian5** [comment]
fix on newer release
